CREATE TABLE discounts (
id INT AUTO_INCREMENT PRIMARY KEY,
product_id INT NOT NULL,
percentage DECIMAL(5, 2) NOT NULL,
start_date DATETIME NOT NULL,
end_date DATETIME NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);